export type Fixture = {
  name: string
  lines: string[]
}

export const fixtures: Fixture[] = [
  {
    name: 'chronological-original',
    lines: [
      'Avery Johnson',
      'avery@example.com | 555-123-4567 | linkedin.com/in/averyjohnson',
      'SUMMARY',
      'Product-minded software engineer with 7 years of experience building reliable internal tools.',
      'TECHNICAL EXPERIENCE',
      'Senior Software Engineer, Northstar Labs | 2021 - Present',
      '- Led React and Node migration that reduced page load time by 38%.',
      '- Built observability dashboards used by 45 operators weekly.',
      'Software Engineer, Greenfield Systems | 2018 - 2021',
      '- Automated release checks and reduced deployment defects by 24%.',
      'TECHNICAL SKILLS',
      'TypeScript, React, Node, SQL, AWS, Docker, Git',
      'EDUCATION',
      'B.S. Computer Science, State University | 2018',
    ],
  },
  {
    name: 'chronological-revised',
    lines: [
      'Avery Johnson',
      'avery@example.com | 555-123-4567 | linkedin.com/in/averyjohnson',
      'SUMMARY',
      'Product-minded software engineer with 7 years of experience building reliable workflow tools.',
      'PROFESSIONAL EXPERIENCE',
      'Senior Software Engineer, Northstar Labs | 2021 - Present',
      '- Led React and Node migration that reduced page load time by 42%.',
      '- Built observability dashboards used by 50 operators weekly.',
      'Software Engineer, Greenfield Systems | 2018 - 2021',
      '- Automated release checks and reduced deployment defects by 24%.',
      'CORE SKILLS',
      'TypeScript, React, Node, SQL, AWS, Git',
      'ACADEMIC BACKGROUND',
      'B.S. Computer Science, State University | 2018',
    ],
  },
  {
    name: 'functional',
    lines: [
      'Jordan Lee',
      'jordan@example.com | 555-222-3333',
      'PROFILE',
      'Operations analyst focused on process improvement and reporting.',
      'CORE SKILLS',
      'Excel, Power BI, SQL, Tableau, stakeholder communication, agile delivery',
      'SELECTED PROJECTS',
      '- Created dashboard suite that saved 12 hours per month.',
      'EMPLOYMENT HISTORY',
      'Operations Analyst, Brightline Health | 2020 - Present',
      'EDUCATION',
      'B.A. Economics, City College | 2020',
    ],
  },
  {
    name: 'hybrid',
    lines: [
      'Morgan Patel',
      'morgan@example.com | 555-444-8888',
      'PROFESSIONAL SUMMARY',
      'Technical program manager with cloud migration and release experience.',
      'TECHNOLOGIES',
      'AWS, Azure, Jira, SQL, Scrum, Terraform',
      'PROFESSIONAL BACKGROUND',
      'Technical Program Manager, Atlas Cloud | 2019 - Present',
      '- Coordinated 18 production releases with zero rollback events.',
      'EDUCATION',
      'M.S. Information Systems, Metro University | 2019',
    ],
  },
  {
    name: 'creative-two-column',
    lines: [
      'Riley Chen | Product Designer | riley@example.com',
      'ABOUT',
      'Designer creating service experiences for healthcare teams.',
      'TOOLS | Figma | Research | Prototyping',
      'EXPERIENCE | Senior Product Designer | 2020 - Present',
      'Designed intake flows that improved completion by 31%.',
      'EDUCATION | B.F.A. Design | 2017',
    ],
  },
  {
    name: 'academic-cv',
    lines: [
      'Dr. Casey Rivera',
      'casey@example.edu | 555-900-1000',
      'RESEARCH',
      'Human-computer interaction, accessibility, and applied machine learning.',
      'PUBLICATIONS',
      '- Rivera C. Accessible Interfaces in Practice. 2024.',
      'TEACHING EXPERIENCE',
      'Lecturer, Example University | 2021 - Present',
      'EDUCATION',
      'Ph.D. Computer Science, Example University | 2021',
    ],
  },
  {
    name: 'federal-style',
    lines: [
      'Taylor Brooks',
      'taylor@example.com | 555-901-3333',
      'WORK EXPERIENCE',
      'Program Analyst, Department Example | GS-12 | 2020 - Present',
      'Hours per week: 40',
      'Supervisor: Jamie Smith, 555-000-0000',
      'Salary: $88,000',
      '- Managed reporting for 7 regional offices.',
      'EDUCATION',
      'B.A. Public Policy, State University | 2016',
    ],
  },
]
